/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Items = {
  ru?: Array<string>;
  en?: Array<string>;
};

export type ListBlockItems = {
  ru?: Array<string>;
  en?: Array<string>;
};

export type QuoteBlock = {
  _type: "quoteBlock";
  title: LocalizedString;
  text: LocalizedText;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageBlock = {
  _type: "imageBlock";
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: LocalizedString;
  caption?: LocalizedString;
};

export type ListBlock = {
  _type: "listBlock";
  items: ListBlockItems;
};

export type TextBlock = {
  _type: "textBlock";
  text: LocalizedText;
};

export type BlockTitle = {
  _type: "blockTitle";
  text: LocalizedString;
};

export type EducationItem = {
  _type: "educationItem";
  institution: LocalizedString;
  program: LocalizedString;
  educationType?:
    | "incomplete-higher"
    | "higher"
    | "professional-development"
    | "course"
    | "secondary-vocational"
    | "custom";
  customEducationType?: LocalizedString;
  period?: LocalizedString;
};

export type WorkExperience = {
  _type: "workExperience";
  company: LocalizedString;
  position: LocalizedString;
  period: LocalizedString;
};

export type SkillGroup = {
  _type: "skillGroup";
  kind: "hard-skills" | "soft-skills" | "languages" | "tools-stack" | "custom";
  title?: LocalizedString;
  showTitle?: boolean;
  items?: Items;
};

export type HomepageContactLink = {
  _type: "homepageContactLink";
  label: LocalizedString;
  href: LocalizedString;
  variant?: "primary" | "secondary";
};

export type ProjectSection = {
  _type: "projectSection";
  title: LocalizedString;
  blocks: Array<
    | ({
        _key: string;
      } & BlockTitle)
    | ({
        _key: string;
      } & TextBlock)
    | ({
        _key: string;
      } & ListBlock)
    | ({
        _key: string;
      } & ImageBlock)
    | ({
        _key: string;
      } & QuoteBlock)
  >;
};

export type ProjectLink = {
  _type: "projectLink";
  label: LocalizedString;
  href: string;
};

export type Experiment = {
  _id: string;
  _type: "experiment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: LocalizedString;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  href: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type LocalizedString = {
  _type: "localizedString";
  ru?: string;
  en?: string;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: LocalizedString;
  slug: Slug;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription: LocalizedText;
  heroDescription: LocalizedText;
  tags?: {
    ru?: Array<string>;
    en?: Array<string>;
  };
  client?: LocalizedString;
  domain?: LocalizedString;
  timeline?: LocalizedString;
  role?: LocalizedString;
  links?: Array<
    {
      _key: string;
    } & ProjectLink
  >;
  sections?: Array<
    {
      _key: string;
    } & ProjectSection
  >;
};

export type LocalizedText = {
  _type: "localizedText";
  ru?: string;
  en?: string;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type ExperimentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "experiment";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  heroAbout: LocalizedText;
  heroContacts?: Array<
    {
      _key: string;
    } & HomepageContactLink
  >;
  skillGroups?: Array<
    {
      _key: string;
    } & SkillGroup
  >;
  workExperienceItems?: Array<
    {
      _key: string;
    } & WorkExperience
  >;
  educationItems?: Array<
    {
      _key: string;
    } & EducationItem
  >;
  middleSectionsOrder: Array<
    "skills" | "projects" | "workExperience" | "education"
  >;
  homepageProjects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
  homepageExperiments?: Array<
    {
      _key: string;
    } & ExperimentReference
  >;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  personName: LocalizedString;
  personRole: LocalizedString;
  personPhoto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seoImageEn?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seoImageRu?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  seoTitle: LocalizedString;
  seoDescription: LocalizedText;
  contactsTitle: LocalizedString;
  contactsButtons?: Array<
    {
      _key: string;
    } & HomepageContactLink
  >;
  showFooterAside?: boolean;
  footerAsideText?: LocalizedString;
  footerAsideLinkLabel?: LocalizedString;
  footerAsideLinkHref?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Items
  | ListBlockItems
  | QuoteBlock
  | SanityImageAssetReference
  | ImageBlock
  | ListBlock
  | TextBlock
  | BlockTitle
  | EducationItem
  | WorkExperience
  | SkillGroup
  | HomepageContactLink
  | ProjectSection
  | ProjectLink
  | Experiment
  | SanityImageCrop
  | SanityImageHotspot
  | LocalizedString
  | Project
  | LocalizedText
  | Slug
  | ProjectReference
  | ExperimentReference
  | Homepage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: projectBySlugQuery
// Query: *[_type == "project" && slug.current in $slugs][0]{    _id,    title,    "slug": slug.current,    coverImage,    shortDescription,    heroDescription,    client,    domain,    timeline,    role,    tags,    "links": coalesce(links, [])[]{      label,      href    },    "sections": coalesce(sections, [])[]{      title,      "blocks": coalesce(blocks, [])[]{        _type,        _key,        _type == "blockTitle" => { "text": text },        _type == "textBlock" => { "text": text },        _type == "listBlock" => { "items": items },        _type == "imageBlock" => { image, alt, caption },        _type == "quoteBlock" => { "quoteHeading": title, text }      }    }  }
export type ProjectBySlugQueryResult = {
  _id: string;
  title: LocalizedString;
  slug: string;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortDescription: LocalizedText;
  heroDescription: LocalizedText;
  client: LocalizedString | null;
  domain: LocalizedString | null;
  timeline: LocalizedString | null;
  role: LocalizedString | null;
  tags: {
    ru?: Array<string>;
    en?: Array<string>;
  } | null;
  links:
    | Array<{
        label: LocalizedString;
        href: string;
      }>
    | Array<never>;
  sections:
    | Array<{
        title: LocalizedString;
        blocks: Array<
          | {
              _type: "blockTitle";
              _key: string;
              text: LocalizedString;
            }
          | {
              _type: "imageBlock";
              _key: string;
              image: {
                asset?: SanityImageAssetReference;
                media?: unknown;
                hotspot?: SanityImageHotspot;
                crop?: SanityImageCrop;
                _type: "image";
              };
              alt: LocalizedString;
              caption: LocalizedString | null;
            }
          | {
              _type: "listBlock";
              _key: string;
              items: ListBlockItems;
            }
          | {
              _type: "quoteBlock";
              _key: string;
              quoteHeading: LocalizedString;
              text: LocalizedText;
            }
          | {
              _type: "textBlock";
              _key: string;
              text: LocalizedText;
            }
        >;
      }>
    | Array<never>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: projectMetadataBySlugQuery
// Query: *[_type == "project" && slug.current in $slugs][0]{    title,    shortDescription  }
export type ProjectMetadataBySlugQueryResult = {
  title: LocalizedString;
  shortDescription: LocalizedText;
} | null;

// Source: sanity/lib/queries.ts
// Variable: projectNavigationItemsQuery
// Query: *[_type == "homepage"] | order(_updatedAt desc)[0]{    "items": coalesce(homepageProjects[]->{ title, "slug": slug.current }, [])  }.items
export type ProjectNavigationItemsQueryResult =
  | Array<{
      title: LocalizedString;
      slug: string;
    }>
  | Array<never>
  | null;

// Source: sanity/lib/queries.ts
// Variable: projectsQuery
// Query: *[_type == "homepage"] | order(_updatedAt desc)[0]{    "items": coalesce(homepageProjects[]->{      _id,      title,      "slug": slug.current,      shortDescription,      tags,      coverImage    }, [])  }.items
export type ProjectsQueryResult =
  | Array<{
      _id: string;
      title: LocalizedString;
      slug: string;
      shortDescription: LocalizedText;
      tags: {
        ru?: Array<string>;
        en?: Array<string>;
      } | null;
      coverImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
    }>
  | Array<never>
  | null;

// Source: sanity/lib/queries.ts
// Variable: homepageProjectSlugsQuery
// Query: *[_type == "homepage"] | order(_updatedAt desc)[0]{    "slugs": coalesce(homepageProjects[]->slug.current, [])  }.slugs
export type HomepageProjectSlugsQueryResult =
  | Array<string>
  | Array<never>
  | null;

// Source: sanity/lib/queries.ts
// Variable: allProjectSlugsQuery
// Query: array::unique(coalesce(*[_type == "project" && defined(slug.current)].slug.current, []))
export type AllProjectSlugsQueryResult = Array<string>;

// Source: sanity/lib/queries.ts
// Variable: homepageQuery
// Query: *[_type == "homepage"] | order(_updatedAt desc)[0]{    _id,    title,    "heroContacts": coalesce(heroContacts[]{ _key, label, href, variant }, []),    heroAbout,    "skillGroups": coalesce(skillGroups[]{ kind, title, showTitle, items }, []),    "workExperienceItems": coalesce(workExperienceItems[]{ _key, company, position, period }, []),    "educationItems": coalesce(educationItems[]{      _key,      institution,      program,      educationType,      customEducationType,      period    }, []),    "middleSectionsOrder": coalesce(middleSectionsOrder, []),    "homepageProjects": coalesce(homepageProjects[]->{      _id,      title,      "slug": slug.current,      shortDescription,      tags,      coverImage    }, []),    "homepageExperiments": coalesce(homepageExperiments[]->{      _id,      title,      image,      href    }, [])  }
export type HomepageQueryResult = {
  _id: string;
  title: string;
  heroContacts:
    | Array<{
        _key: string;
        label: LocalizedString;
        href: LocalizedString;
        variant: "primary" | "secondary" | null;
      }>
    | Array<never>;
  heroAbout: LocalizedText;
  skillGroups:
    | Array<{
        kind:
          | "custom"
          | "hard-skills"
          | "languages"
          | "soft-skills"
          | "tools-stack";
        title: LocalizedString | null;
        showTitle: boolean | null;
        items: Items | null;
      }>
    | Array<never>;
  workExperienceItems:
    | Array<{
        _key: string;
        company: LocalizedString;
        position: LocalizedString;
        period: LocalizedString;
      }>
    | Array<never>;
  educationItems:
    | Array<{
        _key: string;
        institution: LocalizedString;
        program: LocalizedString;
        educationType:
          | "course"
          | "custom"
          | "higher"
          | "incomplete-higher"
          | "professional-development"
          | "secondary-vocational"
          | null;
        customEducationType: LocalizedString | null;
        period: LocalizedString | null;
      }>
    | Array<never>;
  middleSectionsOrder: Array<
    "education" | "projects" | "skills" | "workExperience"
  >;
  homepageProjects:
    | Array<{
        _id: string;
        title: LocalizedString;
        slug: string;
        shortDescription: LocalizedText;
        tags: {
          ru?: Array<string>;
          en?: Array<string>;
        } | null;
        coverImage: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
      }>
    | Array<never>;
  homepageExperiments:
    | Array<{
        _id: string;
        title: LocalizedString | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        href: string;
      }>
    | Array<never>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: experimentsFallbackQuery
// Query: *[_type == "experiment"] | order(_createdAt desc){    _id,    title,    image,    href  }
export type ExperimentsFallbackQueryResult = Array<{
  _id: string;
  title: LocalizedString | null;
  image: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  href: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: homepageExperimentsOrderQuery
// Query: *[_type == "homepage"] | order(_updatedAt desc)[0]{    "ordered": coalesce(homepageExperiments[]->{      _id,      title,      image,      href    }, [])  }
export type HomepageExperimentsOrderQueryResult = {
  ordered:
    | Array<{
        _id: string;
        title: LocalizedString | null;
        image: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        href: string;
      }>
    | Array<never>;
} | null;

// Source: sanity/lib/queries.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings"][0]{    title,    personName,    personRole,    personPhoto,    favicon,    seoImageEn,    seoImageRu,    seoTitle,    seoDescription,    contactsTitle,    "contactsButtons": coalesce(contactsButtons, [])[]{      label,      href,      variant    },    showFooterAside,    footerAsideText,    footerAsideLinkLabel,    footerAsideLinkHref  }
export type SiteSettingsQueryResult = {
  title: string;
  personName: LocalizedString;
  personRole: LocalizedString;
  personPhoto: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seoImageEn: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seoImageRu: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  seoTitle: LocalizedString;
  seoDescription: LocalizedText;
  contactsTitle: LocalizedString;
  contactsButtons:
    | Array<{
        label: LocalizedString;
        href: LocalizedString;
        variant: "primary" | "secondary" | null;
      }>
    | Array<never>;
  showFooterAside: boolean | null;
  footerAsideText: LocalizedString | null;
  footerAsideLinkLabel: LocalizedString | null;
  footerAsideLinkHref: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "project" && slug.current in $slugs][0]{\n    _id,\n    title,\n    "slug": slug.current,\n    coverImage,\n    shortDescription,\n    heroDescription,\n    client,\n    domain,\n    timeline,\n    role,\n    tags,\n    "links": coalesce(links, [])[]{\n      label,\n      href\n    },\n    "sections": coalesce(sections, [])[]{\n      title,\n      "blocks": coalesce(blocks, [])[]{\n        _type,\n        _key,\n        _type == "blockTitle" => { "text": text },\n        _type == "textBlock" => { "text": text },\n        _type == "listBlock" => { "items": items },\n        _type == "imageBlock" => { image, alt, caption },\n        _type == "quoteBlock" => { "quoteHeading": title, text }\n      }\n    }\n  }\n': ProjectBySlugQueryResult;
    '\n  *[_type == "project" && slug.current in $slugs][0]{\n    title,\n    shortDescription\n  }\n': ProjectMetadataBySlugQueryResult;
    '\n  *[_type == "homepage"] | order(_updatedAt desc)[0]{\n    "items": coalesce(homepageProjects[]->{ title, "slug": slug.current }, [])\n  }.items\n': ProjectNavigationItemsQueryResult;
    '\n  *[_type == "homepage"] | order(_updatedAt desc)[0]{\n    "items": coalesce(homepageProjects[]->{\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription,\n      tags,\n      coverImage\n    }, [])\n  }.items\n': ProjectsQueryResult;
    '\n  *[_type == "homepage"] | order(_updatedAt desc)[0]{\n    "slugs": coalesce(homepageProjects[]->slug.current, [])\n  }.slugs\n': HomepageProjectSlugsQueryResult;
    '\n  array::unique(coalesce(*[_type == "project" && defined(slug.current)].slug.current, []))\n': AllProjectSlugsQueryResult;
    '\n  *[_type == "homepage"] | order(_updatedAt desc)[0]{\n    _id,\n    title,\n    "heroContacts": coalesce(heroContacts[]{ _key, label, href, variant }, []),\n    heroAbout,\n    "skillGroups": coalesce(skillGroups[]{ kind, title, showTitle, items }, []),\n    "workExperienceItems": coalesce(workExperienceItems[]{ _key, company, position, period }, []),\n    "educationItems": coalesce(educationItems[]{\n      _key,\n      institution,\n      program,\n      educationType,\n      customEducationType,\n      period\n    }, []),\n    "middleSectionsOrder": coalesce(middleSectionsOrder, []),\n    "homepageProjects": coalesce(homepageProjects[]->{\n      _id,\n      title,\n      "slug": slug.current,\n      shortDescription,\n      tags,\n      coverImage\n    }, []),\n    "homepageExperiments": coalesce(homepageExperiments[]->{\n      _id,\n      title,\n      image,\n      href\n    }, [])\n  }\n': HomepageQueryResult;
    '\n  *[_type == "experiment"] | order(_createdAt desc){\n    _id,\n    title,\n    image,\n    href\n  }\n': ExperimentsFallbackQueryResult;
    '\n  *[_type == "homepage"] | order(_updatedAt desc)[0]{\n    "ordered": coalesce(homepageExperiments[]->{\n      _id,\n      title,\n      image,\n      href\n    }, [])\n  }\n': HomepageExperimentsOrderQueryResult;
    '\n  *[_type == "siteSettings"][0]{\n    title,\n    personName,\n    personRole,\n    personPhoto,\n    favicon,\n    seoImageEn,\n    seoImageRu,\n    seoTitle,\n    seoDescription,\n    contactsTitle,\n    "contactsButtons": coalesce(contactsButtons, [])[]{\n      label,\n      href,\n      variant\n    },\n    showFooterAside,\n    footerAsideText,\n    footerAsideLinkLabel,\n    footerAsideLinkHref\n  }\n': SiteSettingsQueryResult;
  }
}
